apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-deployment
  labels:
    app: proveedor-deployment
spec:
  selector:
    matchLabels:
      app: proveedor-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: proveedor-deployment
    spec:
      containers:
      - name: proveedor-service
        image: imoreira25/ting2_proveedor
        ports:
            - containerPort: 8082
        env:
        - name: spring.cloud.config.uri
          value: http://config-service:8081
        - name: spring.config.import
          value: optional:configserver:http://config-service:8081
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eureka-service:8761/eureka
        - name: EUREKA
          value: eureka-service
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-db
              key: host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-db
              key: name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-user-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: proveedor-service
  labels:
    app: proveedor-service
spec:
  selector:
    app: proveedor-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer